### ISSUE TITLE
My First Bug

### ISSUE THREAD

**Issue by palaheel76** [wtccjava/CSC256PublicChangeMgmt#1]
**Describe the bug**
too many to list

**Program**
all of everything

**Bug Type**
you name it

**Severity**
yes

**Priority**
probably not

**To Reproduce**
1. open program
2. breathe

**Expected behavior**
a miracle

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version unknown

**Additional context**

**Comment by wtccjava** [comment]
Rejected
