### ISSUE TITLE
palaheel76_00001

### ISSUE THREAD

**Issue by palaheel76** [wtccjava/CSC256PublicChangeMgmt#2]
**Describe the bug**
A bug

**Program**
SSA Retirement Age calc

**Component**
By default, all bugs associated with a given component are routed to the lead developer for that component.

**Error Type**
Behavioral error, Documentation error, Design error. 

**Severity**
Fatal, Severe, Minor, Nuisance.

**Priority**
Set by management

**State**
Open/Accepted/Working/Test/Rejected/Deferred/Closed

**To Reproduce**
1. First thing to do
1. Next thing to do
.
.
. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Assigned**
Current owner of the issue.  Initially, assigned to the Component's lead developer.

**Defect Type**
For ODC later.  
One of
* Interface
* Function
* Build/Package/Merge
* Assignment
* Documentation
* Checking
* Algorithm
* Timing/Serialization

**Defect Trigger**
For ODC later.
One of
* Review and Inspection Triggers
* Unit and Function Test Triggers
* System and Field Test Triggers

**Defect Impact**
For ODC later.
One of
* Capability
* Usability
* Performance
* Reliability
* Installability
* Maintainability
* Documentation
* Migration
* Standards
* Integrity/Security

**Comment by wtccjava** [comment]
rejected
